### PR TITLE
Upgrades Zwave2Mqtt to v3.0.2

### PR DESCRIPTION
**Pull request by Munsio**
# Proposed Changes
Upgrade to new minor version

### CODE REVIEW

**Comment by frenck** [comment]
So how did the build go?

**Comment by Munsio** [comment]
Not good, a alpine dependency giving me some headache right now.
I open the PR cause I thought that there is a github pipeline to build the image to confirm if it is a local issue or not.

**Comment by Munsio** [comment]
After a version bump of the base image the build process runs through without issues.
Do you have something like a docker-compose file to test if everything works?

**Comment by Munsio** [comment]
Okay i created one with composer-autodumper. 
Can confirm everything work as it should including that my HVAC finally got their climate profile back so i can control them.

**Comment by Munsio** [comment]
@frenck ping?

**Comment by Munsio** [comment]
@frenck would be great if that PR could be merged soon cause it fixes a few of my problems with HVACs

**Pull request merged**
